
tasks:
  - command: |
      /bin/bash init.sh

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard
    - pivotal.vscode-spring-boot
